server:
  applicationConnectors:
    - type: http
      port: 8080
#    - type: https
#      port: 8443
  adminConnectors:
    - type: http
      port: 8081
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
httpClient:
  timeout: 500ms
  connectionTimeout: 500ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console
#TODO sort out the configuration
swaggerBundleConfiguration:
  resourcePackage: com.elster.booktracker.resources
database:
  driverClass: org.postgresql.Driver
  user: booktracker
  password: tracker3
  url: jdbc:postgresql://localhost/booktracker
  properties:
     charset: UTF-8
     hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute